// Command generateunicode emits the Unicode table the C tokenizer compiles in.
//
// 大文字小文字の畳み込みには出所が 2 つある。C 側はここで作る表、Go 側 (driver/modernc)
// は strings.ToLower で、後者はビルドに使う Go の unicode に追随する。表は生成した時点で
// 凍結されるので、Go が Unicode の版を上げると 2 実装が静かにずれる。
//
// main_test.go がその不一致をテストとして検出する (表の再生成が要ることを教える)。
package main

import (
	"fmt"
	"os"
	"strings"
	"unicode"
	"unicode/utf8"
)

const lowercaseTablePath = "csrc/unicode_lower_table.inc"

// lowercaseTable は Go の unicode から C 用の表を組み立てる。書き出しと検証で同じものを使う。
func lowercaseTable() string {
	var output strings.Builder
	fmt.Fprintf(&output, "/* Generated by go generate; Unicode %s. */\n", unicode.Version)
	for codePoint := rune(0); codePoint <= utf8.MaxRune; codePoint++ {
		lower := unicode.ToLower(codePoint)
		if lower != codePoint {
			fmt.Fprintf(&output, "    {0x%06Xu, 0x%06Xu},\n", codePoint, lower)
		}
	}
	return output.String()
}

func main() {
	if err := os.WriteFile(lowercaseTablePath, []byte(lowercaseTable()), 0o644); err != nil {
		panic(err)
	}
}
