package main

import (
	"fmt"
	"os"
	"strings"
	"unicode"
	"unicode/utf8"
)

func main() {
	var output strings.Builder
	fmt.Fprintf(&output, "/* Generated by go generate; Unicode %s. */\n", unicode.Version)
	for codePoint := rune(0); codePoint <= utf8.MaxRune; codePoint++ {
		lower := unicode.ToLower(codePoint)
		if lower != codePoint {
			fmt.Fprintf(&output, "    {0x%06Xu, 0x%06Xu},\n", codePoint, lower)
		}
	}
	if err := os.WriteFile("csrc/unicode_lower_table.inc", []byte(output.String()), 0o644); err != nil {
		panic(err)
	}
}
